### Get all games
GET http://localhost:3000/api/games

### Get 10 games by page
GET http://localhost:3000/api/games/paginated?page=2&limit=3
Accept: application/json

### Get game by his id
GET http://localhost:3000/api/games/5

### Get game with his bosses by his id
GET http://localhost:3000/api/games/5/boss

### Get game with his trophies by his id
GET http://localhost:3000/api/games/5/trophies

### Get 3 games randomly
GET http://localhost:3000/api/games/random

### Get all games which have to be voted
GET http://localhost:3000/api/games/toVoted

### Get game is played now
GET http://localhost:3000/api/games/isCurrent
