### Get all games
GET http://localhost:3000/api/games

### Get 10 games by page
GET http://localhost:3000/api/games/paginated?page=1&limit=10
Accept: application/json

### Get game by his id
GET http://localhost:3000/api/games/100

### Get 3 games randomly
GET http://localhost:3000/api/games/random

### Get all games which have to be voted
GET http://localhost:3000/api/games/toVoted

### Get game is played now
GET http://localhost:3000/api/games/isCurrent
